name: Model Health Check (CI)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pandas matplotlib

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Analyze metrics
        run: |
          python analyze_metrics.py

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: metrics.csv
